# ccdc-cli: persistent configuration for Windows
# Depends on: common.psm1, detect.psm1

function Read-CcdcConfig {
    if (Test-Path $script:CCDC_CONF) {
        Get-Content $script:CCDC_CONF | ForEach-Object {
            $line = $_.Trim()
            if ($line -match '^#' -or $line -eq '') { return }
            $parts = $line -split '=', 2
            if ($parts.Count -eq 2) {
                $key = $parts[0].Trim()
                $value = $parts[1].Trim()
                switch ($key) {
                    'os'               { $script:CCDC_OS = $value }
                    'os_family'        { $script:CCDC_OS_FAMILY = $value }
                    'os_version'       { $script:CCDC_OS_VERSION = $value }
                    'pkg'              { $script:CCDC_PKG = $value }
                    'fw_backend'       { $script:CCDC_FW_BACKEND = $value }
                    'backup_dir'       { $script:CCDC_BACKUP_DIR = $value }
                    'wazuh_server_ip'  { $script:CCDC_WAZUH_IP = $value }
                    'splunk_server_ip' { $script:CCDC_SPLUNK_IP = $value }
                    'scored_ports_tcp' { $script:CCDC_SCORED_TCP = $value }
                    'scored_ports_udp' { $script:CCDC_SCORED_UDP = $value }
                }
            }
        }
    }

    # Defaults
    if (-not $script:CCDC_BACKUP_DIR) { $script:CCDC_BACKUP_DIR = "C:\ccdc-backups" }
    $script:CCDC_UNDO_DIR = Join-Path $script:CCDC_BACKUP_DIR ".ccdc-undo"
    $script:CCDC_LOG = Join-Path $script:CCDC_BACKUP_DIR "ccdc.log"
}

function Write-CcdcConfig {
    $content = @"
# ccdc-cli config — auto-generated by 'ccdc config init'
# Safe to hand-edit. Delete this file to go back to auto-detect.
# Run: .\ccdc.ps1 config reset

os=$($script:CCDC_OS)
os_family=$($script:CCDC_OS_FAMILY)
os_version=$($script:CCDC_OS_VERSION)
pkg=$($script:CCDC_PKG)
fw_backend=$($script:CCDC_FW_BACKEND)
backup_dir=$($script:CCDC_BACKUP_DIR)
wazuh_server_ip=$($script:CCDC_WAZUH_IP)
splunk_server_ip=$($script:CCDC_SPLUNK_IP)
scored_ports_tcp=$($script:CCDC_SCORED_TCP)
scored_ports_udp=$($script:CCDC_SCORED_UDP)
"@
    Set-Content -Path $script:CCDC_CONF -Value $content
    Write-CcdcLog "Config written to $($script:CCDC_CONF)" -Level Success
}

function Set-CcdcConfigValue {
    param(
        [Parameter(Mandatory)][string]$Key,
        [Parameter(Mandatory)][string]$Value
    )
    if (-not (Test-Path $script:CCDC_CONF)) {
        Write-CcdcLog "No config file. Run '.\ccdc.ps1 config init' first." -Level Error
        return
    }
    $content = Get-Content $script:CCDC_CONF
    $found = $false
    $newContent = $content | ForEach-Object {
        if ($_ -match "^$Key=") {
            $found = $true
            "$Key=$Value"
        } else {
            $_
        }
    }
    if (-not $found) {
        $newContent += "$Key=$Value"
    }
    Set-Content -Path $script:CCDC_CONF -Value $newContent
    Write-CcdcLog "Set $Key=$Value" -Level Success
}

function Show-CcdcConfig {
    Write-Host ""
    Write-Host "Current Configuration:" -ForegroundColor White
    Write-Host "  os             = $($script:CCDC_OS)"
    Write-Host "  os_family      = $($script:CCDC_OS_FAMILY)"
    Write-Host "  os_version     = $($script:CCDC_OS_VERSION)"
    Write-Host "  pkg            = $($script:CCDC_PKG)"
    Write-Host "  fw_backend     = $($script:CCDC_FW_BACKEND)"
    Write-Host "  backup_dir     = $($script:CCDC_BACKUP_DIR)"
    Write-Host "  wazuh_server   = $(if ($script:CCDC_WAZUH_IP) { $script:CCDC_WAZUH_IP } else { '<not set>' })"
    Write-Host "  splunk_server  = $(if ($script:CCDC_SPLUNK_IP) { $script:CCDC_SPLUNK_IP } else { '<not set>' })"
    Write-Host "  scored_tcp     = $(if ($script:CCDC_SCORED_TCP) { $script:CCDC_SCORED_TCP } else { '<not set>' })"
    Write-Host "  scored_udp     = $(if ($script:CCDC_SCORED_UDP) { $script:CCDC_SCORED_UDP } else { '<not set>' })"
    if (Test-Path $script:CCDC_CONF) {
        Write-Host "  config file: $($script:CCDC_CONF)" -ForegroundColor Cyan
    } else {
        Write-Host "  (no config file - using auto-detect)" -ForegroundColor Yellow
    }
}

function Invoke-CcdcConfigInit {
    Write-CcdcLog "Detecting system configuration..." -Level Info
    Invoke-CcdcDetect
    Write-CcdcConfig
    Show-CcdcConfig

    # Create backup directory
    if (-not (Test-Path $script:CCDC_BACKUP_DIR)) {
        New-Item -ItemType Directory -Path $script:CCDC_BACKUP_DIR -Force | Out-Null
    }
    $undoOriginal = Join-Path $script:CCDC_UNDO_DIR "original"
    if (-not (Test-Path $undoOriginal)) {
        New-Item -ItemType Directory -Path $undoOriginal -Force | Out-Null
    }

    # Create baseline if not exists
    $sentinel = Join-Path $undoOriginal ".created"
    if (-not (Test-Path $sentinel)) {
        Invoke-CcdcCreateBaseline
    } else {
        Write-CcdcLog "Baseline already exists - skipping" -Level Info
    }
}

function Reset-CcdcConfig {
    if (Test-Path $script:CCDC_CONF) {
        Remove-Item $script:CCDC_CONF -Force
        Write-CcdcLog "Config file deleted. Will auto-detect on next run." -Level Success
    } else {
        Write-CcdcLog "No config file to delete." -Level Info
    }
}

function Show-CcdcConfigUsage {
    Write-Host ""
    Write-Host "ccdc config - Persistent configuration" -ForegroundColor White
    Write-Host ""
    Write-Host "Commands:"
    Write-Host "  init       Auto-detect and save to .ccdc.conf"
    Write-Host "  set K V    Set a single config value"
    Write-Host "  show       Show current config"
    Write-Host "  reset      Delete config file"
    Write-Host "  edit       Open config file in notepad"
}

function Invoke-CcdcConfig {
    param(
        [string]$Command,
        [string[]]$Args
    )

    if ($script:CCDC_HELP -and -not $Command) {
        Show-CcdcConfigUsage
        return
    }

    switch ($Command) {
        'init'  { Invoke-CcdcConfigInit }
        'set'   {
            if ($Args.Count -lt 2) {
                Write-CcdcLog "Usage: .\ccdc.ps1 config set <key> <value>" -Level Error
                return
            }
            Set-CcdcConfigValue -Key $Args[0] -Value $Args[1]
        }
        'show'  { Show-CcdcConfig }
        'reset' { Reset-CcdcConfig }
        'edit'  {
            if (Test-Path $script:CCDC_CONF) {
                notepad $script:CCDC_CONF
            } else {
                Write-CcdcLog "No config file. Run 'ccdc config init' first." -Level Error
            }
        }
        default { Show-CcdcConfigUsage }
    }
}

Export-ModuleMember -Function Read-CcdcConfig, Write-CcdcConfig, Set-CcdcConfigValue,
    Show-CcdcConfig, Invoke-CcdcConfigInit, Reset-CcdcConfig, Invoke-CcdcConfig
