# ccdc-cli: persistent configuration for Windows
# Depends on: common.psm1, detect.psm1

function Read-CcdcConfig {
    if (Test-Path $global:CCDC_CONF) {
        Get-Content $global:CCDC_CONF | ForEach-Object {
            $line = $_.Trim()
            if ($line -match '^#' -or $line -eq '') { return }
            $parts = $line -split '=', 2
            if ($parts.Count -eq 2) {
                $key = $parts[0].Trim()
                $value = $parts[1].Trim()
                switch ($key) {
                    'os'               { $global:CCDC_OS = $value }
                    'os_family'        { $global:CCDC_OS_FAMILY = $value }
                    'os_version'       { $global:CCDC_OS_VERSION = $value }
                    'pkg'              { $global:CCDC_PKG = $value }
                    'fw_backend'       { $global:CCDC_FW_BACKEND = $value }
                    'backup_dir'       { $global:CCDC_BACKUP_DIR = $value }
                    'wazuh_server_ip'  { $global:CCDC_WAZUH_IP = $value }
                    'splunk_server_ip' { $global:CCDC_SPLUNK_IP = $value }
                    'scored_ports_tcp' { $global:CCDC_SCORED_TCP = $value }
                    'scored_ports_udp' { $global:CCDC_SCORED_UDP = $value }
                    'backup_username'       { $global:CCDC_BACKUP_USERNAME = $value }
                    'passwd_keep_unlocked'  { $global:CCDC_PASSWD_KEEP_UNLOCKED = $value }
                }
            }
        }
    }

    # Defaults
    if (-not $global:CCDC_BACKUP_DIR) { $global:CCDC_BACKUP_DIR = "C:\ccdc-backups" }
    if (-not $global:CCDC_BACKUP_USERNAME) { $global:CCDC_BACKUP_USERNAME = "printer" }
    $global:CCDC_UNDO_DIR = Join-Path $global:CCDC_BACKUP_DIR ".ccdc-undo"
    $global:CCDC_LOG = Join-Path $global:CCDC_BACKUP_DIR "ccdc.log"
}

function Write-CcdcConfig {
    $content = @"
# ccdc-cli config — auto-generated by 'ccdc config init'
# Safe to hand-edit. Delete this file to go back to auto-detect.
# Run: .\ccdc.ps1 config reset

os=$($global:CCDC_OS)
os_family=$($global:CCDC_OS_FAMILY)
os_version=$($global:CCDC_OS_VERSION)
pkg=$($global:CCDC_PKG)
fw_backend=$($global:CCDC_FW_BACKEND)
backup_dir=$($global:CCDC_BACKUP_DIR)
wazuh_server_ip=$($global:CCDC_WAZUH_IP)
splunk_server_ip=$($global:CCDC_SPLUNK_IP)
scored_ports_tcp=$($global:CCDC_SCORED_TCP)
scored_ports_udp=$($global:CCDC_SCORED_UDP)
backup_username=$($global:CCDC_BACKUP_USERNAME)
passwd_keep_unlocked=$($global:CCDC_PASSWD_KEEP_UNLOCKED)
"@
    Set-Content -Path $global:CCDC_CONF -Value $content
    Write-CcdcLog "Config written to $($global:CCDC_CONF)" -Level Success
}

function Set-CcdcConfigValue {
    param(
        [Parameter(Mandatory)][string]$Key,
        [Parameter(Mandatory)][string]$Value
    )
    if (-not (Test-Path $global:CCDC_CONF)) {
        Write-CcdcLog "No config file. Run '.\ccdc.ps1 config init' first." -Level Error
        return
    }
    $content = Get-Content $global:CCDC_CONF
    $found = $false
    $newContent = $content | ForEach-Object {
        if ($_ -match "^$Key=") {
            $found = $true
            "$Key=$Value"
        } else {
            $_
        }
    }
    if (-not $found) {
        $newContent += "$Key=$Value"
    }
    Set-Content -Path $global:CCDC_CONF -Value $newContent
    Write-CcdcLog "Set $Key=$Value" -Level Success
}

function Show-CcdcConfig {
    Write-Host ""
    Write-Host "Current Configuration:" -ForegroundColor White
    Write-Host "  os             = $($global:CCDC_OS)"
    Write-Host "  os_family      = $($global:CCDC_OS_FAMILY)"
    Write-Host "  os_version     = $($global:CCDC_OS_VERSION)"
    Write-Host "  pkg            = $($global:CCDC_PKG)"
    Write-Host "  fw_backend     = $($global:CCDC_FW_BACKEND)"
    Write-Host "  backup_dir     = $($global:CCDC_BACKUP_DIR)"
    Write-Host "  wazuh_server   = $(if ($global:CCDC_WAZUH_IP) { $global:CCDC_WAZUH_IP } else { '<not set>' })"
    Write-Host "  splunk_server  = $(if ($global:CCDC_SPLUNK_IP) { $global:CCDC_SPLUNK_IP } else { '<not set>' })"
    Write-Host "  scored_tcp     = $(if ($global:CCDC_SCORED_TCP) { $global:CCDC_SCORED_TCP } else { '<not set>' })"
    Write-Host "  scored_udp     = $(if ($global:CCDC_SCORED_UDP) { $global:CCDC_SCORED_UDP } else { '<not set>' })"
    Write-Host "  backup_user    = $($global:CCDC_BACKUP_USERNAME)"
    Write-Host "  keep_unlocked  = $(if ($global:CCDC_PASSWD_KEEP_UNLOCKED) { $global:CCDC_PASSWD_KEEP_UNLOCKED } else { '<not set>' })"
    if (Test-Path $global:CCDC_CONF) {
        Write-Host "  config file: $($global:CCDC_CONF)" -ForegroundColor Cyan
    } else {
        Write-Host "  (no config file - using auto-detect)" -ForegroundColor Yellow
    }
}

function Invoke-CcdcConfigInit {
    Write-CcdcLog "Detecting system configuration..." -Level Info
    Invoke-CcdcDetect
    Write-CcdcConfig
    Show-CcdcConfig

    # Create backup directory
    if (-not (Test-Path $global:CCDC_BACKUP_DIR)) {
        New-Item -ItemType Directory -Path $global:CCDC_BACKUP_DIR -Force | Out-Null
    }
    $undoOriginal = Join-Path $global:CCDC_UNDO_DIR "original"
    if (-not (Test-Path $undoOriginal)) {
        New-Item -ItemType Directory -Path $undoOriginal -Force | Out-Null
    }

    # Create baseline if not exists
    $sentinel = Join-Path $undoOriginal ".created"
    if (-not (Test-Path $sentinel)) {
        Invoke-CcdcCreateBaseline
    } else {
        Write-CcdcLog "Baseline already exists - skipping" -Level Info
    }
}

function Reset-CcdcConfig {
    if (Test-Path $global:CCDC_CONF) {
        Remove-Item $global:CCDC_CONF -Force
        Write-CcdcLog "Config file deleted. Will auto-detect on next run." -Level Success
    } else {
        Write-CcdcLog "No config file to delete." -Level Info
    }
}

function Install-CcdcCompletions {
    $completionsFile = Join-Path $global:CCDC_DIR "lib/windows/completions.ps1"
    if (-not (Test-Path $completionsFile)) {
        Write-CcdcLog "Completions file not found: $completionsFile" -Level Error
        return
    }

    # Create ccdc function alias (with admin elevation)
    $ccdcScript = Join-Path $global:CCDC_DIR "ccdc.ps1"
    $functionLine = "function ccdc { & '$ccdcScript' @args }"
    $sourceLine = ". '$completionsFile'"

    # Ensure profile directory exists
    $profileDir = Split-Path $PROFILE
    if (-not (Test-Path $profileDir)) {
        New-Item -ItemType Directory -Path $profileDir -Force | Out-Null
    }

    # Add to profile if not already present
    $needsUpdate = $true
    if (Test-Path $PROFILE) {
        if (Select-String -Path $PROFILE -SimpleMatch "function ccdc" -Quiet) {
            $needsUpdate = $false
        }
    }

    if ($needsUpdate) {
        $block = @"

# ccdc-cli alias and tab completion
$functionLine
$sourceLine
"@
        Add-Content -Path $PROFILE -Value $block
        Write-CcdcLog "Added 'ccdc' function and completions to $PROFILE" -Level Success
        Write-Host ""
        Write-CcdcLog "Restart PowerShell or run:" -Level Info
        Write-Host "  . '$PROFILE'" -ForegroundColor Cyan
        Write-Host ""
        Write-CcdcLog "Then use: ccdc config show" -Level Info
    } else {
        Write-CcdcLog "ccdc function already in $PROFILE" -Level Info
    }
}

function Show-CcdcConfigUsage {
    Write-Host ""
    Write-Host "ccdc config - Persistent configuration" -ForegroundColor White
    Write-Host ""
    Write-Host "Commands:"
    Write-Host "  init                 Auto-detect and save to .ccdc.conf"
    Write-Host "  set K V              Set a single config value"
    Write-Host "  show                 Show current config"
    Write-Host "  reset                Delete config file"
    Write-Host "  edit                 Open config file in notepad"
    Write-Host "  setup-completions    Install 'ccdc' command and tab completion"
}

function Invoke-CcdcConfig {
    param(
        [string]$Command,
        [string[]]$CmdArgs
    )

    if ($global:CCDC_HELP -and -not $Command) {
        Show-CcdcConfigUsage
        return
    }

    switch ($Command) {
        'init'  { Invoke-CcdcConfigInit }
        'set'   {
            if ($CmdArgs.Count -lt 2) {
                Write-CcdcLog "Usage: .\ccdc.ps1 config set <key> <value>" -Level Error
                return
            }
            Set-CcdcConfigValue -Key $CmdArgs[0] -Value $CmdArgs[1]
        }
        'show'  { Show-CcdcConfig }
        'reset' { Reset-CcdcConfig }
        'edit'  {
            if (Test-Path $global:CCDC_CONF) {
                notepad $global:CCDC_CONF
            } else {
                Write-CcdcLog "No config file. Run 'ccdc config init' first." -Level Error
            }
        }
        'setup-completions' { Install-CcdcCompletions }
        default { Show-CcdcConfigUsage }
    }
}

Export-ModuleMember -Function Read-CcdcConfig, Write-CcdcConfig, Set-CcdcConfigValue,
    Show-CcdcConfig, Invoke-CcdcConfigInit, Reset-CcdcConfig, Install-CcdcCompletions,
    Invoke-CcdcConfig
