#!/usr/bin/env bash
# ccdc-cli: persistent configuration via .ccdc.conf
# Depends on: common.sh, detect.sh

# ── Load Config ──

ccdc_config_load() {
    if [[ -f "$CCDC_CONF" ]]; then
        while IFS='=' read -r key value; do
            # Skip comments and blank lines
            [[ "$key" =~ ^[[:space:]]*#.*$ || -z "$key" ]] && continue
            key="$(echo "$key" | tr -d '[:space:]')"
            value="$(echo "$value" | sed 's/^[[:space:]]*//' | sed 's/[[:space:]]*$//')"
            case "$key" in
                os)               CCDC_OS="$value" ;;
                os_family)        CCDC_OS_FAMILY="$value" ;;
                os_version)       CCDC_OS_VERSION="$value" ;;
                pkg)              CCDC_PKG="$value" ;;
                fw_backend)       CCDC_FW_BACKEND="$value" ;;
                backup_dir)       CCDC_BACKUP_DIR="$value" ;;
                wazuh_server_ip)  CCDC_WAZUH_IP="$value" ;;
                splunk_server_ip) CCDC_SPLUNK_IP="$value" ;;
                scored_ports_tcp) CCDC_SCORED_TCP="$value" ;;
                scored_ports_udp) CCDC_SCORED_UDP="$value" ;;
            esac
        done < "$CCDC_CONF"
    fi

    # Apply defaults for anything still unset
    : "${CCDC_BACKUP_DIR:=/ccdc-backups}"
    : "${CCDC_WAZUH_IP:=}"
    : "${CCDC_SPLUNK_IP:=}"
    : "${CCDC_SCORED_TCP:=}"
    : "${CCDC_SCORED_UDP:=}"
    CCDC_UNDO_DIR="${CCDC_BACKUP_DIR}/.ccdc-undo"
    CCDC_LOG="${CCDC_BACKUP_DIR}/ccdc.log"
}

# ── Write Config ──

ccdc_config_write() {
    cat > "$CCDC_CONF" << EOF
# ccdc-cli config — auto-generated by 'ccdc config init'
# Safe to hand-edit. Delete this file to go back to auto-detect.
# Run: ccdc config reset

os=${CCDC_OS}
os_family=${CCDC_OS_FAMILY}
os_version=${CCDC_OS_VERSION}
pkg=${CCDC_PKG}
fw_backend=${CCDC_FW_BACKEND}
backup_dir=${CCDC_BACKUP_DIR}
wazuh_server_ip=${CCDC_WAZUH_IP:-}
splunk_server_ip=${CCDC_SPLUNK_IP:-}
scored_ports_tcp=${CCDC_SCORED_TCP:-}
scored_ports_udp=${CCDC_SCORED_UDP:-}
EOF
    ccdc_log success "Config written to ${CCDC_CONF}"
}

# ── Get Single Value ──

ccdc_config_get() {
    local key="$1"
    if [[ -f "$CCDC_CONF" ]]; then
        grep "^${key}=" "$CCDC_CONF" 2>/dev/null | cut -d= -f2- | sed 's/^[[:space:]]*//'
    fi
}

# ── Set Single Value (sed in-place, preserves comments) ──

ccdc_config_set_value() {
    local key="$1"
    local value="$2"
    if [[ ! -f "$CCDC_CONF" ]]; then
        ccdc_log error "No config file. Run 'ccdc config init' first."
        return 1
    fi
    if grep -q "^${key}=" "$CCDC_CONF"; then
        sed -i "s|^${key}=.*|${key}=${value}|" "$CCDC_CONF"
    else
        echo "${key}=${value}" >> "$CCDC_CONF"
    fi
    ccdc_log success "Set ${key}=${value}"
}

# ── Config Init ──

ccdc_config_init() {
    ccdc_log info "Detecting system configuration..."
    ccdc_detect_all
    ccdc_config_write
    ccdc_config_show

    # Create backup directory structure
    mkdir -p "${CCDC_BACKUP_DIR}"
    mkdir -p "${CCDC_UNDO_DIR}/original"

    # Create Layer 1 baseline (only if not already created)
    if [[ ! -f "${CCDC_UNDO_DIR}/original/.created" ]]; then
        ccdc_undo_create_baseline
    else
        ccdc_log info "Baseline already exists — skipping (run 'ccdc config reset' to recreate)"
    fi
}

# ── Config Show ──

ccdc_config_show() {
    echo -e "${CCDC_BOLD}Current Configuration:${CCDC_NC}"
    echo "  os             = ${CCDC_OS}"
    echo "  os_family      = ${CCDC_OS_FAMILY}"
    echo "  os_version     = ${CCDC_OS_VERSION}"
    echo "  pkg            = ${CCDC_PKG}"
    echo "  fw_backend     = ${CCDC_FW_BACKEND}"
    echo "  backup_dir     = ${CCDC_BACKUP_DIR}"
    echo "  wazuh_server   = ${CCDC_WAZUH_IP:-<not set>}"
    echo "  splunk_server  = ${CCDC_SPLUNK_IP:-<not set>}"
    echo "  scored_tcp     = ${CCDC_SCORED_TCP:-<not set>}"
    echo "  scored_udp     = ${CCDC_SCORED_UDP:-<not set>}"
    if [[ -f "$CCDC_CONF" ]]; then
        echo -e "  ${CCDC_CYAN}config file: ${CCDC_CONF}${CCDC_NC}"
    else
        echo -e "  ${CCDC_YELLOW}(no config file — using auto-detect)${CCDC_NC}"
    fi
}

# ── Config Reset ──

ccdc_config_reset() {
    if [[ -f "$CCDC_CONF" ]]; then
        rm -f "$CCDC_CONF"
        ccdc_log success "Config file deleted. Will auto-detect on next run."
    else
        ccdc_log info "No config file to delete."
    fi
}

# ── Config Edit ──

ccdc_config_edit() {
    if [[ ! -f "$CCDC_CONF" ]]; then
        ccdc_log error "No config file. Run 'ccdc config init' first."
        return 1
    fi
    "${EDITOR:-vi}" "$CCDC_CONF"
}

# ── Config Help ──

ccdc_config_usage() {
    echo -e "${CCDC_BOLD}ccdc config${CCDC_NC} — Persistent configuration"
    echo ""
    echo "Commands:"
    echo "  init       Auto-detect and save to .ccdc.conf"
    echo "  set K V    Set a single config value"
    echo "  show       Show current config"
    echo "  reset      Delete config file (go back to auto-detect)"
    echo "  edit       Open config file in editor"
    echo ""
    echo "Config keys: os, os_family, os_version, pkg, fw_backend,"
    echo "  backup_dir, wazuh_server_ip, splunk_server_ip,"
    echo "  scored_ports_tcp, scored_ports_udp"
}

# ── Config Handler (subcommand router) ──

ccdc_config_handler() {
    local cmd="${1:-}"
    shift 2>/dev/null || true

    if [[ "${CCDC_HELP:-false}" == true && -z "$cmd" ]]; then
        ccdc_config_usage
        return 0
    fi

    case "$cmd" in
        init)
            [[ "${CCDC_HELP:-false}" == true ]] && { echo "Usage: ccdc config init"; return 0; }
            ccdc_config_init "$@"
            ;;
        set)
            [[ "${CCDC_HELP:-false}" == true ]] && { echo "Usage: ccdc config set <key> <value>"; return 0; }
            if [[ $# -lt 2 ]]; then
                ccdc_log error "Usage: ccdc config set <key> <value>"
                return 1
            fi
            ccdc_config_set_value "$1" "$2"
            ;;
        show)
            ccdc_config_show
            ;;
        reset)
            ccdc_config_reset
            ;;
        edit)
            ccdc_config_edit
            ;;
        "")
            ccdc_config_usage
            ;;
        *)
            ccdc_log error "Unknown config command: ${cmd}"
            ccdc_config_usage
            return 1
            ;;
    esac
}
